language: python
services: mongodb
python:
  - "3.6"
install:
  - pip install -r requirements.txt
  - conda install pygraphviz
  - pip install nose
  - pip install coverage
  - pip install python-coveralls
script:
  - nosetests --with-coverage --cover-package=propnet
after_success:
  - coveralls